spring:
  application:
    name: ingredient-service
  sql:
    init:
      mode: always
      data-locations: classpath:test_initial_data.sql
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/nutriodb
    username: postgres_username
    password: postgres_password
    driverClassName: org.postgresql.Driver
    hikari:
      schema: ingredient_test


