spring:
  application:
    name: ingredient-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/nutriodb
    username: postgres_username
    password: postgres_password
    driverClassName: org.postgresql.Driver
    hikari:
      schema: ingredient
#  flyway:
#    user: ingredient_service
#    enabled: true
#    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/nutrioDb
#    password: ingredient_password
#    database: nutrioDb
#    schemas: ingredient_service
#    locations: classpath:db/migration,classpath:db/demo_database
  main:
    banner-mode: off
